---
title: "Ugly Graph"
author: "Nathan Heng"
date: "4/14/2022"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(gsheet)
library(tidyverse)
library(broom)
library(fastDummies)
data <- as_tibble(gsheet2tbl("https://docs.google.com/spreadsheets/d/1QH5XDEUEmBGp2ZzO7OQS0T1vSELIjFAi2gTmnqokoMg/edit#gid=0"))
data$Sweetner <- str_remove(data$Sweetner, "[%]")
  data$Sweetner <- as.numeric(data$Sweetner)
data$MilkFat <- str_remove(data$MilkFat, "[%]")
  data$MilkFat <- as.numeric(data$MilkFat)
  
data$Air <- str_remove(data$Air, "[%]")
  data$Air <- as.numeric(data$Air)
  
m <- lm(Ratings ~  MilkFat + Air + MilkFat:Air, data = data)
Air_values <- unique(data$Air)
MilkFat_values <- unique(data$MilkFat)
predictions <- expand.grid("Air" = Air_values, "MilkFat" = MilkFat_values)
predictions$Ratings <- predict(m, newdata = predictions)
```

```{r}
ggplot(data, aes(x = Air, y = Ratings, fill = as.factor(MilkFat))) + 
  geom_point(shape = 21, size = 4, color = "black") + 
  geom_line(data = predictions, aes(x = Air, y = Ratings, color = as.factor(MilkFat)), size = 1.5) +
  theme(axis.text.x = element_text(size = 20, color = "darkorange"), axis.title.x = element_text(size = 8, color = "purple"),axis.text.y = element_text(size = 8, color = "purple"),  axis.title.y = element_text(size = 20, color = "darkorange"), panel.background = element_rect(fill = "sienna4", color = "blue", size = 10), panel.grid.major = element_line(color = "red"), panel.grid.minor = element_line(color = "red"), legend.title = element_text(size = 8, color = "white"), 
        legend.text = element_text(size = 20, color = "white"), legend.key = element_rect(color = "sienna4", fill = "sienna4"), legend.background = element_rect(fill = "red", colour = "aquamarine", size = 3)) +
  scale_fill_manual("MilkFat", values = c("lawngreen", "hotpink", "cyan")) +
  scale_color_manual("MilkFat", values = c("lawngreen", "hotpink", "cyan"))  
  
```
